GET http://localhost:5281/games

###
GET http://localhost:5281/games/1

###

POST http://localhost:5281/games
Content-Type: application/json

{
    "name": "Mario Odyssey",
    "gender": "PlatformerPlatformerPlatformerPlatformer",
    "price": 159.99,     
    "releaseDate": "2023-10-27"
}

###

PUT http://localhost:5281/games/1
Content-Type: application/json

{
    "name": "street fighter 6",          
    "gender": "Fighting",
    "price": 59.99,
    "releaseDate": "2023-06-02"
}

###
DELETE http://localhost:5281/games/4